name: Update View Count

on:
  workflow_dispatch:  # 可以手动触发
    inputs:
      views:
        description: 'New View Count'
        required: true
        type: number

jobs:
  update_views:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Update views count in views.json
      run: |
        echo "Updating views count..."
        # 获取现有的 views.json
        views=$(cat views.json | jq .views)
        new_views=$((views + 1))
        jq ".views = $new_views" views.json > temp.json && mv temp.json views.json

    - name: Commit and push the updated views.json
      uses: EndBug/add-and-commit@v9
      with:
        author_name: 'github-actions'
        author_email: 'github-actions@users.noreply.github.com'
        message: 'Update view count'
        add: 'views.json'
